# Generated by Django 4.0.5 on 2022-06-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('laptop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=30)),
                ('ram', models.CharField(max_length=20)),
                ('rom', models.CharField(max_length=20)),
                ('HDD', models.CharField(max_length=40)),
            ],
        ),
    ]
