# Generated by Django 4.0.5 on 2022-06-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
