# Generated by Django 4.0.5 on 2022-06-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('bill', models.FloatField()),
            ],
        ),
    ]
