# Generated by Django 4.0.5 on 2022-06-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
    ]
