# Generated by Django 4.0.5 on 2022-06-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_laptop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='description',
            field=models.FileField(blank=True, upload_to='blog_pdf'),
        ),
    ]
